#!/bin/bash

# Script for notifying about the critical events
# Usually this is in the form of a mobile phone SMS-message

# Note: I use an SMS-gateway from a Swedish company called Pixie, you may of course use whatever works for you. /Charlie

# Change the below line to whatever works for you.
curl -s -d account=$SMS_ACCOUNT -d pwd=$SMS_PWD -d receivers=$SMS_RECEIVERS -d sender=Munin --data-urlencode "message=`cat $1`" -d quality=1 http://smsserver.pixie.se/sendsms >/dev/null
