#!/bin/bash

# This script checks to see if a webserver is up and responding with "200 OK".
# Part of the watchdog package, https://github.com/elgholm/watchdog

# Panics:       None
# Criticals:    If URL is not responding or timeouts (second timeout)
# Warnings:     If timeouts

# URL to check
URL=http://www.swedbank-aktiellt.se/

# Quick-and-dirty check, since below curl-solution issues "curl: (56) TCP connection reset by peer" falsely (server is up)
#wget --timeout=10 -qO /dev/null "$URL" || echo "CRITICAL: Apache not responding correctly!"
#exit 0

# Timeouts
WARNING_TIMEOUT=3
CRITICAL_TIMEOUT=10

RCODE=`echo $(curl --write-out %{http_code} --silent -S --connect-timeout $WARNING_TIMEOUT --no-keepalive --output /dev/null $URL)`
case $RCODE in
        000)    echo "WARNING: Apache not responding within $WARNING_TIMEOUT seconds!"
                RCODE=`echo $(curl --write-out %{http_code} --silent -S --connect-timeout $CRITICAL_TIMEOUT --no-keepalive --output /dev/null $URL)`
                case $RCODE in
                        000)    echo "CRITICAL: Apache not responding within $CRITICAL_TIMEOUT seconds!"
                                ;;
                        200)    exit 0
                                ;;
                        *)      echo "CRITICAL: Apache not responding correctly after $WARNING_TIMEOUT seconds timeout! ($RCODE)"
                esac
                ;;
        200)    exit 0
                ;;
        *)      echo "CRITICAL: Apache not responding correctly! ($RCODE)"
esac
