#!/bin/bash

# This script checks to see if a webserver is up and responding with "HTTP/1.1 200 OK".
# Part of the watchdog package, https://github.com/elgholm/watchdog

# History
# 2015-09-22 - First version written by Charlie Elgholm

# Panics:       None
# Criticals:    If URL is not responding
# Warnings:     None

# URL to check
URL=https://www.swedbank-aktiellt.se/pls/casper/pub_uptime

IS_UP=`curl -s --head $URL | head -n 1 | grep -c "HTTP/1.1 200 OK"`
if test $IS_UP -ne 1 ; then
	echo "CRITICAL: Webserver is not responding correctly!"
fi
